Action:
  a1: true
  a2: true
  a3: true
  a4: true
  a5: true
  a6: true
  a7: true
  a8: true
  a9: true
  a10:  true
GPS:
  id: 345
  Size: 9
  String: "&aInitialisation du GPS :"
  String x: "&ax: "
  String y: "&ay: "
  String z: "&az: "
  GPSMenuName: "&aGPS"
  Slot:
    slot1: 0
    slot2: 1
    slot3: 2
    slot4: 3
    slot5: 4
    slot6: 5
    slot7: 6
    slot8: 7
    slot9: 8
    slot10: 9
  Location:
    l1:
      x: 1
      y: 2
      z: 3
    l2:
      x: 4
      y: 5
      z: 6
    l3:
      x: 7
      y: 8
      z: 9
    l4:
      x: 10
      y: 11
      z: 12
    l5:
      x: 10
      y: 11
      z: 12
    l6:
      x: 10
      y: 11
      z: 12
    l7:
      x: 10
      y: 11
      z: 12
    l8:
      x: 10
      y: 11
      z: 12
    l9:
      x: 10
      y: 11
      z: 12
    l10:
      x: 10
      y: 11
      z: 12
  name:
    name1: "&aMine"
    name2: "&aQuartier Pauvre"
    name3: "&aQuartier Riche"
    name4: "&aCampagne de Beaufort"
    name5: "&aQuartier Riche"
    name6: "&aCampagne de Beaufort"
    name7: "&aCampagne de Beaufort"
    name8: "&aCampagne de Beaufort"
    name9: "&aCampagne de Beaufort"
    name10: "&aCampagne de Beaufort"
  ItemStack:
    id1: 1
    id2: 2
    id3: 3
    id4: 4
    id5: 4
    id6: 4
    id7: 4
    id8: 4
    id9: 4
    id10: 4